# Generated by Django 6.0.4 on 2026-04-08 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calorie_goal', models.IntegerField(default=2000, verbose_name='每日卡路里目標')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goal', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '營養目標',
                'verbose_name_plural': '營養目標',
                'db_table': 'diary_nutrition_goal',
            },
        ),
        migrations.CreateModel(
            name='FoodDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200, verbose_name='食物名稱')),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='food_photos/%Y/%m/%d/', verbose_name='食物圖片')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='請輸入食物份量，單位為1', max_digits=6, verbose_name='份量')),
                ('quantity_unit', models.CharField(default='g', help_text='克(g)或毫升(ml)', max_length=20, verbose_name='單位')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='卡路里(kcal)')),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('snack', '宵夜'), ('other', '其他')], max_length=20, verbose_name='進食時段')),
                ('time_end', models.DateTimeField(verbose_name='進食時間')),
                ('remark', models.TextField(blank=True, help_text='備註', verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_diaries', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '飲食紀錄日記',
                'verbose_name_plural': '飲食紀錄日記',
                'db_table': 'diary_food_diary',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-time_end'], name='diary_food__user_id_495f15_idx'), models.Index(fields=['user', 'created_at'], name='diary_food__user_id_9cdbab_idx')],
            },
        ),
    ]
